name: Update Leaderboard

on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "package.json"
      - "next.config.js"
      - ".github/workflows/update-leaderboard.yml"

  schedule:
    - cron: 0 */1 * * *

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        with:
          persist-credentials: false

      - name: Install
        run: |
          npm install

      - name: Build
        run: |
          npm run build-cli
          npm run build
          touch .nojekyll build/.nojekyll
          node cli/update-leaderboard.js
          cp data/leaderboard.json build/leaderboard.json

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: build
          clean: true
